services:
  discord-bot:
    image: ghcr.io/iniwa/discord_tts_bot:latest
    container_name: discord_tts_bot
    tmpfs:
      - /ram_cache
    environment:
      # Portainer上で設定する変数を渡す記述
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: always