services:
  discord-bot:
    build: .
    volumes:
      - ./bot.py:/app/bot.py
      - ./word_dict.json:/app/word_dict.json
      # 音声ファイルのマウント (※同じフォルダに配置してください)
      - ./mei_normal.htsvoice:/voice/mei_normal.htsvoice
    environment:
      - DISCORD_TOKEN=ここにあなたのトークンを入力
    restart: always